-------DEVICE IDs, Do not change unless updated in EFM
devices = {
-- 0 reserved for mainpanel
ELECTRIC_SYSTEM = 1,
WEAPON_SYSTEM 	= 2,
RWR		 		= 3,
LIGHTING		= 4,
UHF_RADIO		= 5,
INTERCOM		= 6,
NVGs			= 7,
AVIONICS		= 8,
DIGITAL_CLOCK 	= 9,
KNEEBOARD 		= 10,
EFM_HELPER 		= 11,
VIDS	 		= 12,
FUEL_SYSTEM		= 13,
Flight_Control	= 14,
BASERADIO		= 15,
ARC182			= 16,
ARGUS7000		= 17,
TACAN			= 18,
RADIO_1         = 19,
RADIO_2         = 20,
TEST_INTERCOM   = 21,
ARC186          = 22,
P_INTERCOM_PANEL= 23,
}